# Generated by Django 5.2.8 on 2025-11-29 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('max_distance', models.IntegerField(verbose_name='Максимальное расстояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField(verbose_name='ID достопримечательности')),
                ('place_name', models.CharField(max_length=200, verbose_name='Название места')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('order', models.IntegerField(verbose_name='Порядок в маршруте')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='main.userroute')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
